config/routes.rb
Rails.application.routes.draw do
  
  resources :spi_files
  resources :open_order_files
  resources :com40s
  resources :com40_files
  resources :orders
  resources :order_files
  resources :product_families
  resources :stock
  resources :stock_files
  resources :plans do
    member do
      get :generate
    end
  end
  resources :operations

  devise_for :users

  resources :products_import

  resources :elements do
    member do
      get :add_operation
    end
  end

  
  resources :products do
    member do
      get :add_element
    end

    collection do
      get :only_new
    end
  end
  resources :machines

  get 'home/index'

  get 'home/new'

  get 'home/create'

  get 'home/update'

  get 'home/index'
  root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/com40.rb
class Com40 < ApplicationRecord
    belongs_to :product
    belongs_to :com40_file
end

app/models/com40_file.rb
class Com40File < ApplicationRecord
    mount_uploader :file, Com40Uploader
    has_many :com40s
    has_many :products, through: :com40s
end

app/models/element.rb
class Element < ApplicationRecord
    belongs_to :product
    has_many :operations
    has_many :machines, through: :operations
end

app/models/machine.rb
class Machine < ApplicationRecord
    has_many :operations
    has_many :elements, through: :operations
end

app/models/open_order.rb
class OpenOrder < ApplicationRecord
    belongs_to :open_order_file
    has_many :open_order_details
    has_many :products, through: :open_order_details
end

app/models/operation.rb
class Operation < ApplicationRecord
include ApplicationHelper

    before_save :calculate_cycle_time

    
    belongs_to :machine
    belongs_to :element

private
    def calculate_cycle_time
        self.cycle_time = 8.0*3600.0/self.efficiency_per_shift
    end

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :order_file
    has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product
end

app/models/order_file.rb
class OrderFile < ApplicationRecord
    mount_uploader :file, OrderFileUploader
    has_many :orders
end

app/models/plan.rb
class Plan < ApplicationRecord
    has_many :production_orders
    has_many :products, :through => :production_orders
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :internal_id_number, presence: true

    has_many :elements
    has_many :stocks
    has_many :com40s
    has_many :order_details
    has_many :open_order_details
    has_many :spis
    has_many :spi_infos
    has_many :production_orders
    has_many :plans, :through => :production_orders

    belongs_to :product_family
    
end

app/models/spi.rb
class Spi < ApplicationRecord
    belongs_to :spi_file
    belongs_to :product
end

app/models/spi_file.rb
class SpiFile < ApplicationRecord
    mount_uploader :file, SpiUploader
    has_many :spis
    has_many :spi_infos
end

app/models/spi_info.rb
class SpiInfo < ApplicationRecord
    belongs_to :product
    belongs_to :spi_file
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :stock_file
    belongs_to :product
end

app/models/stock_file.rb
class StockFile < ApplicationRecord
    mount_uploader :file, StockFileUploader
    has_many :stocks
    has_many :products, through: :stocks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  def index
    @element = Element.all
  end

  def show
    @element = Element.find(params[:id])
  end

  def create
    @element = Element.new(element_params)
    if @element.save
      flash[:notice] = "Dodano nowy element"
      redirect_to product_path(@element.product_id)
    end
  end

  def edit
    @element = Element.find(params[:id])
    @product = Product.find(@element.product_id)
  end

  def update
    @element = Element.find(params[:id])
    if @element.update_attributes(element_params)
      flash[:notice] = "Element został pomyślnie zaktualizowany."
      redirect_to product_path(@element.product_id)
    else
      render action 'edit'
    end
  end

  def destroy
    @element = Element.find(params[:id])
    @element.destroy
    flash[:notice] = "Pomyślnie usunięto element."
    redirect_to product_path(@element.product_id)
  end

  def add_operation
    @element = Element.find(params[:id])
    @operation = @element.operations.new
  end

  def element_params
    params.require(:element).permit( :name, :internal_id_number, :quantity_per_set, :product_id )
  end
end

app/helpers/com40_helper.rb
module Com40Helper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/elements/_form.html.erb
<%= simple_form_for @element do |f| %>
    <%= f.input :name, label: "Nazwa elementu" %>
    <%= f.input :internal_id_number, label: "Numer SWING" %>
    <%= f.input :quantity_per_set, label: "Ilość w komplecie" %>
    <%= f.input :product_id, as: :hidden, input_html: { value: @product.id } %>
    <%= f.button :submit, 'Zapisz', class: "btn btn-primary" %> <%= link_to  "Anuluj", product_path(@product), class: "btn btn-success" %>
<% end %>

app/views/elements/add_operation.html.erb
<h3>Dodawanie operacji dla :</h3>
<h4><%= @element.product.name %></h4>
<h4><%= @element.name %></h4>
<hr>

<%= render partial: "operations/form" %>

app/views/elements/edit.html.erb
<h3>Edycja elementu należącego do produktu <%= @element.product.name %> </h3>
<%= render partial: "form" %>

app/views/elements/index.html.erb
<h1>Elements#index</h1>
<p>Find me in app/views/elements/index.html.erb</p>

app/views/elements/new.html.erb
<h3>Dodaj element</h3>

app/views/elements/show.html.erb
<h3>Produkt: <%= @element.product.name %></h3>
<h4>Element: <%= @element.name %></h4>
<h4>Ilość elementów w komplecie: <%= @element.quantity_per_set %></h4>
<h4>Numer elementu: <%= @element.internal_id_number %></h4>
<%= link_to  "Wróć do produktu", product_path(@element.product_id), class: "btn btn-success" %>

<hr>

<h3>Lista operacji</h3>
<% if user_signed_in? %>
    <%= link_to  "Dodaj operację", add_operation_element_path(@element.id), class: "btn btn-primary" %>
<% else %>
    Zaloguj się by dodać operacje
<% end %>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Nazwa operacji</th>
            <th>Maszyna</th>
            <th>Wydajność na zmianę</th>
            <th>Czas cyklu</th>
            <th>Akcje</th>
        </tr>
    </thead>
    <tbody>
        <% @element.operations.each do |operation| %>
        <tr>
            <td><%= operation.id %></td>
            <td><%= operation.name %></td>
            <td><%= operation.machine.name %></td>
            <td><%= operation.efficiency_per_shift %></td>
            <td><%= operation.cycle_time %></td>
            <td>
                <% if user_signed_in? %>
                    <%= link_to  "Edytuj", edit_operation_path(operation), class: "btn btn-primary btn-xs" %>
                    <%= link_to  "Usuń", operation_path(operation), method: :delete, class: "btn btn-danger btn-xs" %>
                <% else %>
                    Akcje dostępne po zalogowaniu.
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>