config/routes.rb
Rails.application.routes.draw do
  
  resources :spi_files
  resources :open_order_files
  resources :com40s
  resources :com40_files
  resources :orders
  resources :order_files
  resources :product_families
  resources :stock
  resources :stock_files
  resources :plans do
    member do
      get :generate
    end
  end
  resources :operations

  devise_for :users

  resources :products_import

  resources :elements do
    member do
      get :add_operation
    end
  end

  
  resources :products do
    member do
      get :add_element
    end

    collection do
      get :only_new
    end
  end
  resources :machines

  get 'home/index'

  get 'home/new'

  get 'home/create'

  get 'home/update'

  get 'home/index'
  root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/com40.rb
class Com40 < ApplicationRecord
    belongs_to :product
    belongs_to :com40_file
end

app/models/com40_file.rb
class Com40File < ApplicationRecord
    mount_uploader :file, Com40Uploader
    has_many :com40s
    has_many :products, through: :com40s
end

app/models/element.rb
class Element < ApplicationRecord
    belongs_to :product
    has_many :operations
    has_many :machines, through: :operations
end

app/models/machine.rb
class Machine < ApplicationRecord
    has_many :operations
    has_many :elements, through: :operations
end

app/models/open_order.rb
class OpenOrder < ApplicationRecord
    belongs_to :open_order_file
    has_many :open_order_details
    has_many :products, through: :open_order_details
end

app/models/operation.rb
class Operation < ApplicationRecord
include ApplicationHelper

    before_save :calculate_cycle_time

    
    belongs_to :machine
    belongs_to :element

private
    def calculate_cycle_time
        self.cycle_time = 8.0*3600.0/self.efficiency_per_shift
    end

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :order_file
    has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product
end

app/models/order_file.rb
class OrderFile < ApplicationRecord
    mount_uploader :file, OrderFileUploader
    has_many :orders
end

app/models/plan.rb
class Plan < ApplicationRecord
    has_many :production_orders
    has_many :products, :through => :production_orders
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :internal_id_number, presence: true

    has_many :elements
    has_many :stocks
    has_many :com40s
    has_many :order_details
    has_many :open_order_details
    has_many :spis
    has_many :spi_infos
    has_many :production_orders
    has_many :plans, :through => :production_orders

    belongs_to :product_family
    
end

app/models/spi.rb
class Spi < ApplicationRecord
    belongs_to :spi_file
    belongs_to :product
end

app/models/spi_file.rb
class SpiFile < ApplicationRecord
    mount_uploader :file, SpiUploader
    has_many :spis
    has_many :spi_infos
end

app/models/spi_info.rb
class SpiInfo < ApplicationRecord
    belongs_to :product
    belongs_to :spi_file
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :stock_file
    belongs_to :product
end

app/models/stock_file.rb
class StockFile < ApplicationRecord
    mount_uploader :file, StockFileUploader
    has_many :stocks
    has_many :products, through: :stocks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  def index
    @machines = Machine.all
  end

  def new
    @machine = Machine.new
  end

  def create
    @machine = Machine.new(machine_params)
    if @machine.save
      flash[:notice] = "Dodano nową maszynę"
      redirect_to machines_path
    else
      render action: 'new'
    end
  end

  def edit
    @machine = Machine.find(params[:id])
  end

  def update
    @machine = Machine.find(params[:id])
    if @machine.update_attributes(machine_params)
      flash[:notice] = "Maszyna pomyślnie zaktualizowana"
      redirect_to machines_path
    else
      render action: 'edit'
    end
  end

  def show
    @machine = Machine.find(params[:id])
    @spis = Spi.where(spi_file_id: SpiFile.last).all
    # @spis = Spi.where(spi_file_id: 27).all
    @current_week_num = Time.now.year.to_s + Time.now.strftime('%W').to_s
    @order_details = OrderDetail.all
  end

  def machine_params
    #TODO zmienić parametry permit
    params.require(:machine).permit(:name, :factory, :OEE )    
  end
end

app/helpers/com40_helper.rb
module Com40Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
    def display_as_percent(value)
        result = value * 100
        return "#{result}%"
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/machines/_form.html.erb
<%= simple_form_for @machine do |f| %>
    <%= f.input :name, label: "Nazwa maszyny" %>
    <%= f.input :factory, label: "Fabryka" %>
    <%= f.input :OEE, label: "Wskaźnik OEE" %>
    <%= f.button :submit, 'Zapisz', class: "btn btn-primary" %>
<% end %>

app/views/machines/edit.html.erb
<h3>Edytuj dane maszyny</h3>
<%= render  "form" %>

app/views/machines/index.html.erb
<h3>Lista maszyn</h3>
<% if user_signed_in? %>
<%= link_to  "Dodaj nową maszynę", new_machine_path, class: "btn btn-success" %>
<% else %>
Zaloguj się by dodać maszyny
<% end %>


    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Nazwa maszyny</th>
                <th>Fabryka</th>
                <th>Wskaźnik OEE</th>
                <th>Akcje</th>
            </tr>
        </thead>
        <tbody>
            <% @machines.each do |machine| %>
                <tr>
                    <td>
                        <%= machine.id %>
                    </td>
                    <td>
                        <%= machine.name %>
                    </td>
                    <td>
                        <%= machine.factory %>
                    </td>
                    <td>
                        <%= machine.OEE.present? ? display_as_percent(machine.OEE) : 0 %>
                    </td>
                    <td>
                        <%= link_to  "Pokaż", machine_path(machine), class: "btn btn-default btn-xs" %>
                        <% if user_signed_in? %>
                            <%= link_to  "Edytuj", edit_machine_path(machine), class: "btn btn-primary btn-xs" %>
                            <%= link_to  "Usuń", machine_path(machine), method: :delete, class: "btn btn-danger btn-xs" %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

app/views/machines/new.html.erb
<h3>Dodawanie nowej maszyny</h3>
<%= render partial: "form" %>

app/views/machines/show.html.erb
<h3>Nazwa maszyny: <%= @machine.name %></h3>

<p>Fabryka: <%= @machine.factory %></p>
<p>Wskaźnik OEE: <%= display_as_percent(@machine.OEE) %></p>
<%= link_to  "Powrót do listy maszyn", machines_path, class: "btn btn-primary" %>


<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="3"></th>
            <th class="text-center" colspan="2"><%= @current_week_num %></th>
            <th class="text-center" colspan="2"><%= @current_week_num.to_i + 1 %></th>
            <th class="text-center" colspan="2"><%= @current_week_num.to_i + 2 %></th>
            <th class="text-center" colspan="2"><%= @current_week_num.to_i + 3 %></th>
        </tr>
        <tr>
            <th>Produkt</th>
            <th>Element</th>
            <th>Operacja</th>
            <th>SPI</th>
            <th>Zam</th>
            <th>SPI</th>
            <th>Zam</th>
            <th>SPI</th>
            <th>Zam</th>
            <th>SPI</th>
            <th>Zam</th>
        </tr>
    </thead>
    <tbody>
        <% @machine.elements.each do |element| %>
        <tr>
            <td><%= element.product.name %></td>
            <td><%= element.name %></td>
            <td><%= element.operations.where(machine: @machine).first.name %></td>

            <td><%= @spis.where(week: @current_week_num).where(product_id: element.product.id).first.present? ? @spis.where(week: @current_week_num).where(product_id: element.product.id).first.qty : 0 %></td>
            <td><%= @order_details.where(product: element.product).where(orig_week: @current_week_num).first.present? ? @order_details.where(product: element.product).where(orig_week: @current_week_num).sum(:orig_qty) : 0 %></td>

            <td><%= @spis.where(week: @current_week_num.to_i + 1).where(product: element.product).first.present? ? @spis.where(week: @current_week_num.to_i + 1).where(product_id: element.product.id).first.qty : 0 %></td>
            <td><%= @order_details.where(product: element.product).where(orig_week: @current_week_num.to_i + 1).first.present? ? @order_details.where(product: element.product).where(orig_week: @current_week_num.to_i + 1).sum(:orig_qty) : 0 %></td>
            
            <td><%= @spis.where(week: @current_week_num.to_i + 2).where(product: element.product).first.present? ? @spis.where(week: @current_week_num.to_i + 2).where(product_id: element.product.id).first.qty : 0 %></td>
            <td><%= @order_details.where(product: element.product).where(orig_week: @current_week_num.to_i + 2).first.present? ? @order_details.where(product: element.product).where(orig_week: @current_week_num.to_i + 2).sum(:orig_qty) : 0 %></td>

            <td><%= @spis.where(week: @current_week_num.to_i + 3).where(product: element.product).first.present? ? @spis.where(week: @current_week_num.to_i + 3).where(product_id: element.product.id).first.qty : 0 %></td>
            <td><%= @order_details.where(product: element.product).where(orig_week: @current_week_num.to_i + 3).first.present? ? @order_details.where(product: element.product).where(orig_week: @current_week_num.to_i + 3).sum(:orig_qty) : 0 %></td>
            
        </tr>
        <% end %>
    </tbody>
</table>