config/routes.rb
Rails.application.routes.draw do
  
  resources :spi_files
  resources :open_order_files
  resources :com40s
  resources :com40_files
  resources :orders
  resources :order_files
  resources :product_families
  resources :stock
  resources :stock_files
  resources :plans do
    member do
      get :generate
    end
  end
  resources :operations

  devise_for :users

  resources :products_import

  resources :elements do
    member do
      get :add_operation
    end
  end

  
  resources :products do
    member do
      get :add_element
    end

    collection do
      get :only_new
    end
  end
  resources :machines

  get 'home/index'

  get 'home/new'

  get 'home/create'

  get 'home/update'

  get 'home/index'
  root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/com40.rb
class Com40 < ApplicationRecord
    belongs_to :product
    belongs_to :com40_file
end

app/models/com40_file.rb
class Com40File < ApplicationRecord
    mount_uploader :file, Com40Uploader
    has_many :com40s
    has_many :products, through: :com40s
end

app/models/element.rb
class Element < ApplicationRecord
    belongs_to :product
    has_many :operations
    has_many :machines, through: :operations
end

app/models/machine.rb
class Machine < ApplicationRecord
    has_many :operations
    has_many :elements, through: :operations
end

app/models/open_order.rb
class OpenOrder < ApplicationRecord
    belongs_to :open_order_file
    has_many :open_order_details
    has_many :products, through: :open_order_details
end

app/models/operation.rb
class Operation < ApplicationRecord
include ApplicationHelper

    before_save :calculate_cycle_time

    
    belongs_to :machine
    belongs_to :element

private
    def calculate_cycle_time
        self.cycle_time = 8.0*3600.0/self.efficiency_per_shift
    end

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :order_file
    has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product
end

app/models/order_file.rb
class OrderFile < ApplicationRecord
    mount_uploader :file, OrderFileUploader
    has_many :orders
end

app/models/plan.rb
class Plan < ApplicationRecord
    has_many :production_orders
    has_many :products, :through => :production_orders
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :internal_id_number, presence: true

    has_many :elements
    has_many :stocks
    has_many :com40s
    has_many :order_details
    has_many :open_order_details
    has_many :spis
    has_many :spi_infos
    has_many :production_orders
    has_many :plans, :through => :production_orders

    belongs_to :product_family
    
end

app/models/spi.rb
class Spi < ApplicationRecord
    belongs_to :spi_file
    belongs_to :product
end

app/models/spi_file.rb
class SpiFile < ApplicationRecord
    mount_uploader :file, SpiUploader
    has_many :spis
    has_many :spi_infos
end

app/models/spi_info.rb
class SpiInfo < ApplicationRecord
    belongs_to :product
    belongs_to :spi_file
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :stock_file
    belongs_to :product
end

app/models/stock_file.rb
class StockFile < ApplicationRecord
    mount_uploader :file, StockFileUploader
    has_many :stocks
    has_many :products, through: :stocks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy ]
  
  def index
    @products = Product.page(params[:page]).per(50)
  end

  def only_new
    @products = Product.where(
      internal_id_number: "Brak").page(params[:page]).per(50)
    render action: "index"
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Dodano nowy produkt"
      redirect_to products_path
    else
      render action: 'new'
    end

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:notice] = "Produkt pomyślnie zaktualizowany."
      redirect_to products_path
    else
      render action: 'edit'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_element
    @product = Product.find(params[:id])
    @element = @product.elements.new
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Pomyślnie usunięto produkt"
    redirect_to products_path
  end

  def product_params
    params.require(:product).permit(:name, 
      :customer_id_number, 
      :internal_id_number, :color, 
      :quantity_on_palet, 
      :product_family_id, 
      :page, :min_production, 
      :max_production, :min_stock, 
      :max_stock, 
      :lack_group, 
      :size, 
      :palet_size, 
      :status, 
      :max_orders_per_week, 
      :lead_time, 
      :average_spi, 
      :average_sale, 
      :average_order_qty )
  end
  

end

app/helpers/com40_helper.rb
module Com40Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/products/_form.html.erb
<div class="row">
     
<%= simple_form_for @product do |f| %>
    
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    
    <%= f.input :name, label: "Nazwa produktu" %>
    <%= f.association :product_family %>
    <%= f.input :customer_id_number, label: "Numer klienta" %>
    <%= f.input :internal_id_number, label: "Numer swing" %>
    <%= f.input :size, label: "Wymiary" %>
    <%= f.input :color, label: "Kolor" %>
    <%= f.input :lack_group, label: "Grupa koloru na lakierni"%>
    
    </div>
    
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    <%= f.input :quantity_on_palet, label: "Ilość na palecie" %>
    <%= f.input :palet_size, label: "Wielkość palety" %>
    <%= f.input :max_orders_per_week, label: "Maksymalna ilość zamówień w tygodniu" %>
    <%= f.input :lead_time, label: "Czas przejścia w zmianach" %>
    <%= f.input :min_production, label: "Minimalna partia produkcyjna" %>
    <%= f.input :max_production, label: "Maksymalna partia produkcyjna" %>
    <%= f.input :min_stock, label: "Minimalny zapas magazynowy" %>
    <%= f.input :max_stock, label: "Maksymalny zapas magazynowy" %>
    </div>

    <%= f.button :submit, 'Zapisz', class: "btn btn-primary" %> <%= link_to  "Anuluj", products_path, class: "btn btn-success" %>
<% end %></div>

app/views/products/add_element.html.erb
<h3>Dodawanie elementów do produktu <%= @product.name %></h3>

<%= render partial: "elements/form" %>

app/views/products/edit.html.erb
<h3>Edycja produktu</h3>
<%= render partial:  "form" %>

app/views/products/index.html.erb
<h3>Lista produktów</h3>

<% if user_signed_in? %>
    <p><%= link_to  "Dodaj nowy produkt", new_product_path, class: "btn btn-success" %></p>
<% else %>
    <p>Zaloguj się by dodać produkty</p>
<% end %>


<%= paginate @products, outer_window: 2 %>
<ul class="nav nav-tabs">
    <li <% if params[:action] == "index" %> class="active" <% end %>><%= link_to  "Wszystkie", products_path %></li>
    <li <% if params[:action] == "only_new" %> class="active" <% end %>><%= link_to  "Tylko nowe", only_new_products_path %></li>
</ul>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Nazwa produktu</th>
            <th>Rodzina</th>
            <th>Numer klienta</th>
            <th>Numer Swing</th>
            <th>Kolor</th>
            <th>Ilość na palecie</th>
            <th>Min. produkcja</th>
            <th>Max. produkcja</th>
            <th>Min. zapas</th>
            <th>Max. zapas</th>
            <!-- <th>Akcje</th> -->
        </tr>
    </thead>
    <tbody>
        <% @products.each do |product| %>
            <tr>
                <td><%= product.id %></td>
                <td><%= product.name %></td>
                <td><%= product.product_family.name %></td>
                <td><%= product.customer_id_number %></td>
                <td><%= product.internal_id_number %></td>
                <td><%= product.color %></td>
                <td><%= product.quantity_on_palet %></td>
                <td><%= product.min_production %></td>
                <td><%= product.max_production %></td>
                <td><%= product.min_stock %></td>
                <td><%= product.max_stock %></td>
            </tr>
            <tr>
                <td colspan="11"> <%= link_to  "Pokaż", product_path(product), class: "btn btn-default btn-xs"  %>
                    
                    <% if user_signed_in? %>
                        <%= link_to  "Edytuj", edit_product_path(product), class: "btn btn-primary btn-xs" %>
                        <%= link_to  "Usuń", product_path(product), method: :delete, class: "btn btn-danger btn-xs", data: { confirm: "Czy na pewno chcesz usunąć ten produkt" } %>
                    <% end %> </td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= paginate @products, outer_window: 2 %>

app/views/products/new.html.erb
<h3>Dodawanie nowego produktu</h3>
<%= render  partial: "form", locals: {button_name: "Dodaj nowy produkt"} %>

app/views/products/show.html.erb
<h3>Produkt: <%= @product.name %></h3>
<h4>Numenr klienta: <%= @product.customer_id_number %></h4>
<h4>Wewnętrzny numer: <%= @product.internal_id_number %></h4>
<h4>Kolor: <%= @product.color %></h4>
<h4>Ilość na palecie: <%= @product.quantity_on_palet %></h4>
<h4>Grupa lakierni: <%= @product.lack_group %></h4>
<h4>Wielkość palety: <%= @product.palet_size %></h4>
<%= link_to  "Wróć do listy produktów", products_path, class: "btn btn-success" %>
<hr>

<h3>Lista elementów</h3>
<% if user_signed_in? %>
<%= link_to  "Dodaj element", add_element_product_path(@product.id), class: "btn btn-primary" %>
<% else %>
Zaloguj się by dodać elementy
<% end %>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Nazwa elementu</th>
            <th>Numer swing</th>
            <th>Ilość na komplet</th>
            <th>Akcje</th>
        </tr>
    </thead>
    <tbody>
        <% @product.elements.each do |element| %>
            <tr>
                <td><%= element.id %></td>
                <td><%= element.name %></td>
                <td><%= element.internal_id_number %></td>
                <td><%= element.quantity_per_set %></td>
                <td>
                    <%= link_to  "Pokaż", element_path(element), class: "btn btn-default btn-xs" %>
                    <% if user_signed_in? %>
                        <%= link_to  "Edytuj", edit_element_path(element), class: "btn btn-primary btn-xs" %>
                        <%= link_to  "Usuń", element_path(element), method: :delete, class: "btn btn-danger btn-xs" %>
                    <% end %>
            </td>
            </tr>
        <% end %>
    </tbody>
</table>