config/routes.rb
Rails.application.routes.draw do
  
  resources :spi_files
  resources :open_order_files
  resources :com40s
  resources :com40_files
  resources :orders
  resources :order_files
  resources :product_families
  resources :stock
  resources :stock_files
  resources :plans do
    member do
      get :generate
    end
  end
  resources :operations

  devise_for :users

  resources :products_import

  resources :elements do
    member do
      get :add_operation
    end
  end

  
  resources :products do
    member do
      get :add_element
    end

    collection do
      get :only_new
    end
  end
  resources :machines

  get 'home/index'

  get 'home/new'

  get 'home/create'

  get 'home/update'

  get 'home/index'
  root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/com40.rb
class Com40 < ApplicationRecord
    belongs_to :product
    belongs_to :com40_file
end

app/models/com40_file.rb
class Com40File < ApplicationRecord
    mount_uploader :file, Com40Uploader
    has_many :com40s
    has_many :products, through: :com40s
end

app/models/element.rb
class Element < ApplicationRecord
    belongs_to :product
    has_many :operations
    has_many :machines, through: :operations
end

app/models/machine.rb
class Machine < ApplicationRecord
    has_many :operations
    has_many :elements, through: :operations
end

app/models/open_order.rb
class OpenOrder < ApplicationRecord
    belongs_to :open_order_file
    has_many :open_order_details
    has_many :products, through: :open_order_details
end

app/models/operation.rb
class Operation < ApplicationRecord
include ApplicationHelper

    before_save :calculate_cycle_time

    
    belongs_to :machine
    belongs_to :element

private
    def calculate_cycle_time
        self.cycle_time = 8.0*3600.0/self.efficiency_per_shift
    end

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :order_file
    has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product
end

app/models/order_file.rb
class OrderFile < ApplicationRecord
    mount_uploader :file, OrderFileUploader
    has_many :orders
end

app/models/plan.rb
class Plan < ApplicationRecord
    has_many :production_orders
    has_many :products, :through => :production_orders
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :internal_id_number, presence: true

    has_many :elements
    has_many :stocks
    has_many :com40s
    has_many :order_details
    has_many :open_order_details
    has_many :spis
    has_many :spi_infos
    has_many :production_orders
    has_many :plans, :through => :production_orders

    belongs_to :product_family
    
end

app/models/spi.rb
class Spi < ApplicationRecord
    belongs_to :spi_file
    belongs_to :product
end

app/models/spi_file.rb
class SpiFile < ApplicationRecord
    mount_uploader :file, SpiUploader
    has_many :spis
    has_many :spi_infos
end

app/models/spi_info.rb
class SpiInfo < ApplicationRecord
    belongs_to :product
    belongs_to :spi_file
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :stock_file
    belongs_to :product
end

app/models/stock_file.rb
class StockFile < ApplicationRecord
    mount_uploader :file, StockFileUploader
    has_many :stocks
    has_many :products, through: :stocks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.page(params[:page]).per(50)
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      flash[:notice] = "Dodano nowy plan produkcji"
      redirect_to plan_path(@plan.id)
    else
      render action: 'new'
    end
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update

  end

  def generate
    @plan = Plan.find(params[:id])
    if generate_production_plan(@plan)
      flash[:notice] = "Wygenerowano nowy plan produkcji"
      redirect_to plan_path(@plan.id)
    else
      flash[:error] = "Nie udało się wygenerować planu produkcji"
    end
  end

  def plan_params
    params.require(:plan).permit(:final_date)
  end

  def generate_production_plan(plan)
    result = PlanGenerator.new(plan).call
    return result
  end
end

app/helpers/com40_helper.rb
module Com40Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/plans/_form.html.erb
<%= simple_form_for @plan do |f| %>
    <%= f.input :final_date, label: "Końcowa data realizacji" %>

    <%= f.button :submit, 'Zapisz', class: "btn btn-primary" %><%= link_to  "Anuluj", plans_path, class: "btn btn-success" %>
<% end %>

app/views/plans/edit.html.erb
<h1>Plans#edit</h1>
<p>Find me in app/views/plans/edit.html.erb</p>

app/views/plans/index.html.erb
<h3>Plany produkcyjne</h3>

<% if user_signed_in? %>
    <p><%= link_to  "Utwórz nowy plan produkcji", new_plan_path, class: "btn btn-success" %></p>
<% else %>
    <p>Zaloguj się by dodać plan produkcji.</p>
<% end %>

<%= paginate @plans, outer_window: 2 %>


<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Numer planu</th>
            <th>Data utworzenia</th>
            <th>Data ostatniej modyfikacji</th>
            <th>Data realizacji</th>
            <th>Akcje</th>
        </tr>
    </thead>
    <tbody>
        <% @plans.each do |plan| %>
        <tr>
            <td><%= plan.id %></td>
            <td><%= plan.created_at %></td>
            <td><%= plan.updated_at %></td>
            <td><%= plan.final_date %></td>
            <td>
                <%= link_to  "Pokaż", plan_path(plan), class: "btn btn-default btn-xs" %>
                <% if user_signed_in? %>
                    <%= link_to  "Edytuj", edit_plan_path(plan), class: "btn btn-primary btn-xs" %>
                    <%= link_to  "Usuń", plan_path(plan), method: :delete, class: "btn btn-danger btn-xs" %>
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>




<%= paginate @plans, outer_window: 2 %>

app/views/plans/new.html.erb
<h3>Dodawanie nowego planu produkcyjnego</h3>
<%= render partial: "form" %>

app/views/plans/show.html.erb
<h3>Plan produkcji. Termin realizacji <%= @plan.final_date %></h3>

<% if @plan.production_orders.first == nil %>
    <%= link_to  "Generuj plan produkcji", generate_plan_path(@plan.id), class: "btn btn-success" %>
<% end %>


<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Numer Ikea</th>
            <th>Numer SWING</th>
            <th>Nazwa produktu</th>
            <th>Status zamówienia</th>
            <th>Ilość</th>
        </tr>
    </thead>
    <tbody>
        <% @plan.production_orders.each do |production_order| %>
            <tr>
                <td><%= production_order.product.customer_id_number %></td>
                <td><%= production_order.product.internal_id_number %></td>
                <td><%= production_order.product.name %></td>
                <td><%= production_order.status %></td>
                <td><%= production_order.ordered_qty %></td>
            </tr>
        <% end %>
    </tbody>
</table>